Repository math-comp/math-comp, pull requests merged in 2018-12, with the labels that each got.

#252 Fix some new warnings emitted by Coq 8.10
  mathcomp/algebra/fraction.v
  mathcomp/algebra/intdiv.v
  mathcomp/algebra/interval.v
  mathcomp/algebra/mxalgebra.v
  mathcomp/algebra/mxpoly.v
  mathcomp/algebra/polydiv.v
  mathcomp/algebra/rat.v
  mathcomp/algebra/ssralg.v
  mathcomp/algebra/ssrint.v
  mathcomp/algebra/ssrnum.v
  mathcomp/algebra/vector.v
  mathcomp/character/character.v
  mathcomp/character/classfun.v
  mathcomp/character/mxabelem.v
  mathcomp/field/algC.v
  mathcomp/field/algnum.v
  mathcomp/field/closed_field.v
  mathcomp/field/cyclotomic.v
  mathcomp/fingroup/automorphism.v
  mathcomp/fingroup/fingroup.v
  mathcomp/fingroup/morphism.v
  mathcomp/fingroup/perm.v
  mathcomp/solvable/abelian.v
  mathcomp/solvable/center.v
  mathcomp/ssreflect/bigop.v
  mathcomp/ssreflect/div.v
  mathcomp/ssreflect/eqtype.v
  mathcomp/ssreflect/fingraph.v
  mathcomp/ssreflect/finset.v
  mathcomp/ssreflect/fintype.v
  mathcomp/ssreflect/generic_quotient.v
  mathcomp/ssreflect/prime.v
  mathcomp/ssreflect/seq.v
  mathcomp/ssreflect/ssrnat.v
Labels: kind: build

#260 fix TFAE
  mathcomp/ssreflect/seq.v
Labels: kind: fix, needs: review

#264 Correct and improve implicits and documentation of MatrixGenField
  ChangeLog
  mathcomp/character/mxrepresentation.v
Labels: kind: documentation, kind: refactoring

#201 Generalizing homo-mono-morphism lemmas and extremum
  ChangeLog
  mathcomp/algebra/ssrint.v
  mathcomp/algebra/ssrnum.v
  mathcomp/ssreflect/eqtype.v
  mathcomp/ssreflect/fintype.v
  mathcomp/ssreflect/path.v
  mathcomp/ssreflect/seq.v
  mathcomp/ssreflect/ssrnat.v
Labels: kind: enhancement, needs: rebase, needs: review
