Repository math-comp/math-comp, pull requests merged in 2020-11, with the labels that each got.

#483 Adding lemma PermSleq1 to perm.v
  CHANGELOG_UNRELEASED.md
  mathcomp/fingroup/perm.v
Labels: kind: enhancement

#629 Remove the mc_1_9 compat module
  CHANGELOG_UNRELEASED.md
  mathcomp/ssreflect/ssrnat.v
Labels: kind: clean-up

#633 Delaying the deprecation of `iter_add`
  mathcomp/ssreflect/ssrnat.v
Labels: kind: fix

#632 Reorganize, generalize, and add lemmas about `path`, `cycle`, and `sorted`
  CHANGELOG_UNRELEASED.md
  mathcomp/ssreflect/path.v
  mathcomp/ssreflect/seq.v
Labels: kind: enhancement

#640 Deprecation of iota_add delayed, and not the one of iter_add
  mathcomp/ssreflect/seq.v
  mathcomp/ssreflect/ssrnat.v
Labels: kind: fix

#641 Replace `exact:` with `apply:` in `Hint Extern` declarations
  mathcomp/algebra/ssrnum.v
Labels: kind: fix

#647 Fix CHANGELOG entries for #604, #611, and #624
  CHANGELOG_UNRELEASED.md
Labels: kind: fix

#646 Rename `eq_sorted` lemmas to `sorted_eq` and generalize `sort_le_id`
  CHANGELOG_UNRELEASED.md
  mathcomp/ssreflect/bigop.v
  mathcomp/ssreflect/binomial.v
  mathcomp/ssreflect/order.v
  mathcomp/ssreflect/path.v
  mathcomp/ssreflect/prime.v
Labels: kind: fix

#636 `comm(Cmx|_mxC)` -> `comm(_scalar_mx|_mx_scalar)`
  CHANGELOG_UNRELEASED.md
  mathcomp/algebra/matrix.v
  mathcomp/algebra/mxalgebra.v
  mathcomp/algebra/mxpoly.v
Labels: kind: fix

#586 Maximal rank and full rank row submatrices
  CHANGELOG_UNRELEASED.md
  mathcomp/algebra/mxalgebra.v
Labels: kind: enhancement

#599 Intro pattern extensions for dup, swap and apply
  .gitlab-ci.yml
  CHANGELOG_UNRELEASED.md
  mathcomp/algebra/ssrnum.v
  mathcomp/ssreflect/ssreflect.v
  mathcomp/test_suite/test_intro_rw.v
Labels: drops: coq 8.9, kind: enhancement

#650 Refactor, reshuffle, and rename sorting lemmas in `path.v`
  CHANGELOG_UNRELEASED.md
  mathcomp/ssreflect/fintype.v
  mathcomp/ssreflect/path.v
Labels: kind: refactoring

#656 add declare scopes
  mathcomp/Make
  mathcomp/_CoqProject
  mathcomp/algebra/Make
  mathcomp/algebra/mxalgebra.v
  mathcomp/algebra/poly.v
  mathcomp/algebra/ssralg.v
  mathcomp/algebra/ssrint.v
  mathcomp/algebra/vector.v
  mathcomp/character/Make
  mathcomp/character/classfun.v
  mathcomp/character/mxabelem.v
  mathcomp/character/mxrepresentation.v
  mathcomp/field/Make
  mathcomp/field/algC.v
  mathcomp/field/algnum.v
  mathcomp/field/falgebra.v
  mathcomp/fingroup/Make
  mathcomp/fingroup/action.v
  mathcomp/fingroup/fingroup.v
  mathcomp/fingroup/presentation.v
  mathcomp/solvable/Make
  mathcomp/solvable/gfunctor.v
  mathcomp/solvable/gseries.v
  mathcomp/solvable/jordanholder.v
  mathcomp/ssreflect/Make
  mathcomp/ssreflect/bigop.v
  mathcomp/ssreflect/eqtype.v
  mathcomp/ssreflect/finset.v
  mathcomp/ssreflect/fintype.v
  mathcomp/ssreflect/generic_quotient.v
  mathcomp/ssreflect/order.v
  mathcomp/ssreflect/seq.v
  mathcomp/ssreflect/ssrAC.v
  mathcomp/ssreflect/ssrnat.v
Labels: kind: fix

#659 Removing unused cpo_sort scope
  mathcomp/ssreflect/order.v
Labels: kind: bug

#663 Using Arguments / to deal with volatile definitions
  mathcomp/algebra/matrix.v
  mathcomp/algebra/mxalgebra.v
  mathcomp/algebra/poly.v
  mathcomp/algebra/ssralg.v
  mathcomp/character/character.v
  mathcomp/character/classfun.v
  mathcomp/solvable/gfunctor.v
Labels: kind: refactoring

#661 Tuning simplifications using Arguments nomatch
  CHANGELOG_UNRELEASED.md
  mathcomp/field/closed_field.v
  mathcomp/ssreflect/binomial.v
  mathcomp/ssreflect/choice.v
  mathcomp/ssreflect/prime.v
  mathcomp/ssreflect/seq.v
  mathcomp/ssreflect/ssrnat.v
Labels: kind: enhancement, kind: fix

#672 Fixing [dup] and [swap] for Coq 8.12
  mathcomp/ssreflect/ssreflect.v
  mathcomp/test_suite/test_intro_rw.v
Labels: kind: fix

#670 Fix deprecation notations in path.v
  mathcomp/ssreflect/path.v
Labels: kind: bug, kind: fix

#664 Fix `@maxr` and `@minr`
  CHANGELOG_UNRELEASED.md
  mathcomp/algebra/ssrnum.v
Labels: kind: clean-up, kind: fix

#671 Transpose `join_idP(l|r)` lemmas to follow the naming convention
  CHANGELOG_UNRELEASED.md
  mathcomp/ssreflect/order.v
Labels: kind: bug, kind: fix

#601 Add `_in` variants of the sorting lemmas
  CHANGELOG_UNRELEASED.md
  mathcomp/ssreflect/path.v
  mathcomp/ssreflect/seq.v
  mathcomp/ssreflect/ssrbool.v
Labels: kind: enhancement

#665 Generalize `allrel` to take two lists as arguments
  CHANGELOG_UNRELEASED.md
  mathcomp/algebra/matrix.v
  mathcomp/field/falgebra.v
  mathcomp/field/separable.v
  mathcomp/ssreflect/path.v
  mathcomp/ssreflect/seq.v
Labels: kind: enhancement

#674 Using `only printing` and fixing coercion in notations
  CHANGELOG_UNRELEASED.md
  mathcomp/Makefile.test-suite.coq.local
  mathcomp/algebra/ssrint.v
  mathcomp/ssreflect/eqtype.v
  mathcomp/ssreflect/finset.v
  mathcomp/ssreflect/fintype.v
  mathcomp/test_suite/imset2_finset.v
  mathcomp/test_suite/imset2_finset.v.out
  mathcomp/test_suite/imset2_gproduct.v
  mathcomp/test_suite/imset2_gproduct.v.out
Labels: kind: clean-up, kind: fix
