Repository math-comp/math-comp, pull requests merged in 2020-04, with the labels that each got.

#472 minor documentation fix
  mathcomp/solvable/finmodule.v
Labels: kind: documentation

#211 Rewriting with AC (not modulo AC), using a small scale command.
  CHANGELOG_UNRELEASED.md
  mathcomp/Make
  mathcomp/Make.test-suite
  mathcomp/algebra/fraction.v
  mathcomp/algebra/ssrnum.v
  mathcomp/ssreflect/Make
  mathcomp/ssreflect/all_ssreflect.v
  mathcomp/ssreflect/ssrAC.v
  mathcomp/test_suite/test_ssrAC.v
Labels: kind: enhancement, needs: propagation

#477 Move the contents of Good Practices to CONTIBUTING.md
  CONTRIBUTING.md
Labels: kind: documentation

#221 Some more lemmas on permutations
  CHANGELOG_UNRELEASED.md
  mathcomp/fingroup/action.v
  mathcomp/fingroup/perm.v
  mathcomp/solvable/finmodule.v
Labels: kind: enhancement
