Repository math-comp/math-comp, pull requests merged in 2020-09, with the labels that each got.

#559 Adding sig_big_dep lemma
  CHANGELOG_UNRELEASED.md
  mathcomp/ssreflect/bigop.v
Labels: kind: enhancement

#557 chore: refactor GitLab CI config a bit to lighten nightly builds
  .gitlab-ci.yml
Labels: kind: CI

#562 Adding [row|col]_[udlr]submx lemmas
  CHANGELOG_UNRELEASED.md
  mathcomp/algebra/matrix.v
Labels: kind: enhancement

#567 split_find_nth and split_find lemmas
  CHANGELOG_UNRELEASED.md
  mathcomp/ssreflect/path.v
  mathcomp/ssreflect/seq.v
Labels: kind: enhancement

#433 [test suite] infrastructure to test how some statements are printed
  .gitignore
  .gitlab-ci.yml
  mathcomp/Make.test-suite
  mathcomp/Makefile.common
  mathcomp/Makefile.test-suite.coq.local
  mathcomp/test_suite/output.v
  mathcomp/test_suite/output.v.out
  mathcomp/test_suite/output.v.out.8.7
  mathcomp/test_suite/output.v.out.8.8
  mathcomp/test_suite/output.v.out.8.9
Labels: kind: CI

#484 Putting `ord1` in `fintype.v`
  CHANGELOG_UNRELEASED.md
  mathcomp/algebra/zmodp.v
  mathcomp/fingroup/perm.v
  mathcomp/ssreflect/fintype.v
Labels: kind: enhancement

#592 Fix naming inconsistencies between `imset` and `map` lemmas.
  CHANGELOG_UNRELEASED.md
  mathcomp/character/classfun.v
  mathcomp/character/inertia.v
  mathcomp/character/integral_char.v
  mathcomp/character/vcharacter.v
  mathcomp/fingroup/action.v
  mathcomp/fingroup/automorphism.v
  mathcomp/fingroup/fingroup.v
  mathcomp/fingroup/gproduct.v
  mathcomp/fingroup/morphism.v
  mathcomp/fingroup/perm.v
  mathcomp/fingroup/quotient.v
  mathcomp/solvable/abelian.v
  mathcomp/solvable/center.v
  mathcomp/solvable/commutator.v
  mathcomp/solvable/cyclic.v
  mathcomp/solvable/extremal.v
  mathcomp/solvable/finmodule.v
  mathcomp/solvable/hall.v
  mathcomp/solvable/jordanholder.v
  mathcomp/solvable/maximal.v
  mathcomp/solvable/primitive_action.v
  mathcomp/ssreflect/binomial.v
  mathcomp/ssreflect/finset.v
  mathcomp/ssreflect/ssrfun.v
Labels: kind: refactoring

#585 Kernel lemmas
  CHANGELOG_UNRELEASED.md
  mathcomp/algebra/mxpoly.v
Labels: kind: enhancement
