Repository math-comp/math-comp, pull requests merged in 2020-10, with the labels that each got.

#612 Add new iteration/bigop lemmas and export existing ones in ssralg
  CHANGELOG_UNRELEASED.md
  mathcomp/algebra/ssralg.v
Labels: kind: enhancement, kind: fix

#618 Stability by commutation
  CHANGELOG_UNRELEASED.md
  mathcomp/algebra/mxalgebra.v
  mathcomp/algebra/mxpoly.v
Labels: kind: enhancement

#625 Fix ssrnat
  mathcomp/ssreflect/ssrnat.v
Labels: kind: fix
