Repository math-comp/math-comp, pull requests merged in 2021-06, with the labels that each got.

#649 Add sorting lemmas specialized for `porderType` and `orderType`
  CHANGELOG_UNRELEASED.md
  mathcomp/ssreflect/order.v
Labels: kind: enhancement

#712 Diagonalization of endormorphisms
  CHANGELOG_UNRELEASED.md
  mathcomp/algebra/mxpoly.v
Labels: kind: enhancement

#753 intdiv.v : Fixed the doc + removed unused import
  mathcomp/algebra/intdiv.v
Labels: kind: documentation, kind: fix

#754 Canonical additive, linear and rmorphism for fst and snd
  CHANGELOG_UNRELEASED.md
  mathcomp/algebra/ssralg.v
  mathcomp/field/separable.v
Labels: kind: enhancement

#740 Fix some inheritance issues
  CHANGELOG_UNRELEASED.md
  etc/utils/hierarchy.ml
  mathcomp/algebra/finalg.v
  mathcomp/algebra/ssrnum.v
Labels: kind: fix
