Repository math-comp/math-comp, pull requests merged in 2021-01, with the labels that each got.

#690 erroneous deprecation warning
  mathcomp/algebra/polydiv.v
Labels: kind: fix

#680 Add `pairwise` predicate and some missing lemmas
  CHANGELOG_UNRELEASED.md
  mathcomp/ssreflect/path.v
  mathcomp/ssreflect/seq.v
Labels: kind: enhancement

#686 Drop support for Coq 8.10
  .github/workflows/nix.yml
  .gitlab-ci.yml
  CHANGELOG_UNRELEASED.md
  coq-mathcomp-ssreflect.opam
  mathcomp/Makefile.common
  mathcomp/algebra/intdiv.v
  mathcomp/algebra/interval.v
  mathcomp/algebra/matrix.v
  mathcomp/algebra/mxalgebra.v
  mathcomp/algebra/poly.v
  mathcomp/algebra/polydiv.v
  mathcomp/algebra/ssralg.v
  mathcomp/algebra/ssrint.v
  mathcomp/algebra/ssrnum.v
  mathcomp/algebra/vector.v
  mathcomp/character/classfun.v
  mathcomp/fingroup/action.v
  mathcomp/fingroup/perm.v
  mathcomp/ssreflect/bigop.v
  mathcomp/ssreflect/div.v
  mathcomp/ssreflect/finset.v
  mathcomp/ssreflect/fintype.v
  mathcomp/ssreflect/order.v
  mathcomp/ssreflect/path.v
  mathcomp/ssreflect/prime.v
  mathcomp/ssreflect/seq.v
  mathcomp/ssreflect/ssreflect.v
  mathcomp/ssreflect/ssrnat.v
Labels: drops: coq 8.10, kind: clean-up

#696 Adding lemma sumnB
  CHANGELOG_UNRELEASED.md
  mathcomp/ssreflect/bigop.v
Labels: kind: enhancement
