Repository math-comp/math-comp, pull requests merged in 2021-07, with the labels that each got.

#759 [bigop] Add lemma for boolean enumeration in bigops
  CHANGELOG_UNRELEASED.md
  mathcomp/ssreflect/bigop.v
Labels: kind: enhancement

#765 Don't rename argument of section variable
  mathcomp/fingroup/fingroup.v
Labels: kind: clean-up

#501 Intro pattern extensions for rewrite
  CHANGELOG_UNRELEASED.md
  mathcomp/algebra/finalg.v
  mathcomp/algebra/intdiv.v
  mathcomp/algebra/matrix.v
  mathcomp/algebra/mxpoly.v
  mathcomp/algebra/ssrnum.v
  mathcomp/character/character.v
  mathcomp/character/classfun.v
  mathcomp/character/inertia.v
  mathcomp/character/integral_char.v
  mathcomp/character/mxabelem.v
  mathcomp/character/mxrepresentation.v
  mathcomp/field/algebraics_fundamentals.v
  mathcomp/field/algnum.v
  mathcomp/field/falgebra.v
  mathcomp/field/finfield.v
  mathcomp/field/galois.v
  mathcomp/field/separable.v
  mathcomp/fingroup/action.v
  mathcomp/fingroup/automorphism.v
  mathcomp/fingroup/fingroup.v
  mathcomp/fingroup/gproduct.v
  mathcomp/fingroup/morphism.v
  mathcomp/fingroup/perm.v
  mathcomp/solvable/abelian.v
  mathcomp/solvable/alt.v
  mathcomp/solvable/burnside_app.v
  mathcomp/solvable/center.v
  mathcomp/solvable/cyclic.v
  mathcomp/solvable/extraspecial.v
  mathcomp/solvable/extremal.v
  mathcomp/solvable/finmodule.v
  mathcomp/solvable/frobenius.v
  mathcomp/solvable/gseries.v
  mathcomp/solvable/jordanholder.v
  mathcomp/solvable/maximal.v
  mathcomp/solvable/primitive_action.v
  mathcomp/solvable/sylow.v
  mathcomp/ssreflect/bigop.v
  mathcomp/ssreflect/binomial.v
  mathcomp/ssreflect/eqtype.v
  mathcomp/ssreflect/finfun.v
  mathcomp/ssreflect/fingraph.v
  mathcomp/ssreflect/finset.v
  mathcomp/ssreflect/fintype.v
  mathcomp/ssreflect/path.v
  mathcomp/ssreflect/seq.v
  mathcomp/ssreflect/ssrbool.v
  mathcomp/ssreflect/ssreflect.v
Labels: drops: coq 8.9, kind: enhancement

#768 Update CHANGELOG.md
  CHANGELOG.md
Labels: kind: documentation

#769 Update and rename AUTHORS to INITIAL_AUTHORS.md
  AUTHORS
  INITIAL_AUTHORS.md
Labels: kind: documentation

#764 gitignore mathcomp/test_suite/test_hierarchy_all.v
  .gitignore
Labels: kind: fix
