Repository math-comp/math-comp, pull requests merged in 2021-03, with the labels that each got.

#710 Adding Order.enum and related definitions and theorems
  CHANGELOG_UNRELEASED.md
  mathcomp/ssreflect/order.v
  mathcomp/ssreflect/seq.v
Labels: kind: enhancement

#708 Silencing Hint Locality warning
  mathcomp/Make
  mathcomp/_CoqProject
  mathcomp/algebra/Make
  mathcomp/character/Make
  mathcomp/field/Make
  mathcomp/fingroup/Make
  mathcomp/solvable/Make
  mathcomp/ssreflect/Make
Labels: kind: fix, kind: warning

#720 Adding sorting on tuples.
  CHANGELOG_UNRELEASED.md
  mathcomp/ssreflect/tuple.v
Labels: kind: enhancement

#707 Silencing warning deprecated-ident-entry
  mathcomp/Make
  mathcomp/_CoqProject
  mathcomp/algebra/Make
  mathcomp/character/Make
  mathcomp/field/Make
  mathcomp/fingroup/Make
  mathcomp/solvable/Make
  mathcomp/ssreflect/Make
Labels: kind: fix, kind: warning

#728 Update path.v
  mathcomp/ssreflect/path.v
Labels: kind: documentation, kind: fix
