Repository math-comp/math-comp, pull requests merged in 2022-06, with the labels that each got.

#878 Remove old compatibility code for Coq < 8.13
  CHANGELOG_UNRELEASED.md
  mathcomp/solvable/gseries.v
  mathcomp/ssreflect/eqtype.v
  mathcomp/ssreflect/ssrbool.v
  mathcomp/ssreflect/ssreflect.v
  mathcomp/ssreflect/ssrfun.v
Labels: kind: clean-up

#824 Fix the scope of `{ 'symbol' ... }` notations
  CHANGELOG_UNRELEASED.md
  mathcomp/algebra/fraction.v
  mathcomp/algebra/poly.v
  mathcomp/algebra/ring_quotient.v
  mathcomp/algebra/ssralg.v
  mathcomp/fingroup/action.v
  mathcomp/fingroup/morphism.v
  mathcomp/ssreflect/order.v
  mathcomp/ssreflect/tuple.v
Labels: kind: fix

#902 Suffix infix
  CHANGELOG_UNRELEASED.md
  mathcomp/ssreflect/seq.v
Labels: kind: enhancement

#891 Remove hint-without-locality warnings
  CHANGELOG_UNRELEASED.md
  _CoqProject
  mathcomp/Make
  mathcomp/_CoqProject
  mathcomp/algebra/Make
  mathcomp/algebra/fraction.v
  mathcomp/algebra/intdiv.v
  mathcomp/algebra/matrix.v
  mathcomp/algebra/mxalgebra.v
  mathcomp/algebra/polydiv.v
  mathcomp/algebra/rat.v
  mathcomp/algebra/ssrnum.v
  mathcomp/algebra/vector.v
  mathcomp/character/Make
  mathcomp/character/classfun.v
  mathcomp/field/Make
  mathcomp/field/algC.v
  mathcomp/field/algnum.v
  mathcomp/field/cyclotomic.v
  mathcomp/fingroup/Make
  mathcomp/fingroup/automorphism.v
  mathcomp/fingroup/fingroup.v
  mathcomp/solvable/Make
  mathcomp/ssreflect/Make
  mathcomp/ssreflect/bigop.v
  mathcomp/ssreflect/div.v
  mathcomp/ssreflect/eqtype.v
  mathcomp/ssreflect/fingraph.v
  mathcomp/ssreflect/finset.v
  mathcomp/ssreflect/fintype.v
  mathcomp/ssreflect/generic_quotient.v
  mathcomp/ssreflect/order.v
  mathcomp/ssreflect/prime.v
  mathcomp/ssreflect/seq.v
  mathcomp/ssreflect/ssrnat.v
  mathcomp/ssreflect/tuple.v
Labels: kind: warning
