Repository math-comp/math-comp, pull requests merged in 2022-07, with the labels that each got.

#904 Adapt w.r.t. coq/coq#16004 after the merge of #813.
  mathcomp/ssreflect/ssreflect.v
Labels: kind: clean-up

#906 Deploy `mathcomp/mathcomp-dev:coq-8.16` & Add ci-analysis-dev job anew
  .gitlab-ci.yml
  coq-mathcomp-ssreflect.opam
Labels: kind: CI

#810 [CI] First attempt to document Nix CI
  README-CI-Nix.md
Labels: kind: documentation
