Repository math-comp/math-comp, pull requests merged in 2023-11, with the labels that each got.

#1114 Adapt to https://github.com/coq/coq/pull/17576
  mathcomp/algebra/qpoly.v
Labels: TODO: MC-1 port

#1126 Cleanup ssralg and galois
  mathcomp/algebra/ssralg.v
  mathcomp/field/galois.v
Labels: TODO: MC-1 port

#1121 contrib order
  CHANGELOG_UNRELEASED.md
  mathcomp/ssreflect/finset.v
  mathcomp/ssreflect/order.v
Labels: TODO: MC-1 port

#986 Generalize ler_sqrt
  CHANGELOG_UNRELEASED.md
  mathcomp/algebra/ssrnum.v
Labels: TODO: MC-1 port, needs: squashing

#1046 Cleanup phantom types
  CHANGELOG_UNRELEASED.md
  mathcomp/algebra/finalg.v
  mathcomp/algebra/fraction.v
  mathcomp/algebra/matrix.v
  mathcomp/algebra/poly.v
  mathcomp/algebra/qpoly.v
  mathcomp/algebra/ring_quotient.v
  mathcomp/algebra/ssralg.v
  mathcomp/algebra/vector.v
  mathcomp/character/classfun.v
  mathcomp/character/mxabelem.v
  mathcomp/field/falgebra.v
  mathcomp/field/fieldext.v
  mathcomp/fingroup/fingroup.v
  mathcomp/fingroup/perm.v
  mathcomp/fingroup/quotient.v
  mathcomp/solvable/alt.v
  mathcomp/solvable/cyclic.v
  mathcomp/solvable/gseries.v
  mathcomp/ssreflect/eqtype.v
  mathcomp/ssreflect/finset.v
  mathcomp/ssreflect/generic_quotient.v
  mathcomp/ssreflect/order.v
Labels: kind: clean-up, needs: coq 8.18
