Repository math-comp/math-comp, pull requests merged in 2023-09, with the labels that each got.

#1057 Fix GitLab CI/CD config
  .gitlab-ci.yml
  coq-mathcomp-ssreflect.opam
Labels: kind: CI

#1069 fixes #1063
  CHANGELOG_UNRELEASED.md
  mathcomp/algebra/ssrnum.v
  mathcomp/field/algebraics_fundamentals.v
  mathcomp/field/finfield.v
  mathcomp/ssreflect/order.v
Labels: kind: refactoring, TODO: MC-1 port

#1072 [CI] Remove mention to coq-master branch of HB
  .nix/config.nix
Labels: kind: CI, TODO: MC-1 port

#1074 Remove Program Definition
  mathcomp/algebra/ssralg.v
  mathcomp/ssreflect/order.v
Labels: kind: clean-up

#1075 rm 2.0.0 deprecation warnings
  mathcomp/field/qfpoly.v
Labels: kind: clean-up

#1076 fixes #997
  CHANGELOG_UNRELEASED.md
  mathcomp/algebra/rat.v
  mathcomp/algebra/ssrint.v
Labels: kind: clean-up, TODO: MC-1 port

#1077 feat: Use the latest coqorg/coq:8.18.0 within mathcomp-dev CI/CD
  .gitlab-ci.yml
Labels: kind: CI

#1080 [CI] Update Nix toolbox
  .github/workflows/nix-action-coq-8.16.yml
  .github/workflows/nix-action-coq-8.17.yml
  .github/workflows/nix-action-coq-8.18.yml
  .github/workflows/nix-action-coq-master.yml
  .nix/coq-nix-toolbox.nix
Labels: TODO: MC-1 port

#1070 Remove "x : p" notation
  mathcomp/fingroup/presentation.v
  mathcomp/solvable/extraspecial.v
  mathcomp/solvable/extremal.v
Labels: TODO: MC-1 port

#1052 Parse negative number constants in ssralg
  CHANGELOG_UNRELEASED.md
  mathcomp/algebra/ssralg.v
  mathcomp/algebra/ssrint.v
  mathcomp/field/algC.v
Labels: TODO: MC-1 port

#1082 Update doc after https://github.com/math-comp/math-comp/pull/1052
  mathcomp/algebra/ssrint.v
Labels: TODO: MC-1 port
