Repository math-comp/math-comp, pull requests merged in 2023-06, with the labels that each got.

#682 Rework of PR #281: Archimedean structures on top of num/real domain/field/closedField
  .nix/config.nix
  CHANGELOG_UNRELEASED.md
  mathcomp/Make
  mathcomp/algebra/Make
  mathcomp/algebra/archimedean.v
  mathcomp/algebra/intdiv.v
  mathcomp/algebra/rat.v
  mathcomp/algebra/ssrint.v
  mathcomp/algebra/ssrnum.v
  mathcomp/character/character.v
  mathcomp/character/classfun.v
  mathcomp/character/inertia.v
  mathcomp/character/integral_char.v
  mathcomp/character/vcharacter.v
  mathcomp/field/algC.v
  mathcomp/field/algebraics_fundamentals.v
  mathcomp/field/algnum.v
  mathcomp/field/cyclotomic.v
  mathcomp/field/finfield.v
Labels: kind: enhancement

#1039 fixes #1037
  etc/porting_to_mathcomp2/porting.pdf
  etc/porting_to_mathcomp2/porting.tex
Labels: kind: documentation

#1042 units_Zp is cyclic
  CHANGELOG_UNRELEASED.md
  mathcomp/solvable/cyclic.v
Labels: needs: rebase

#1040 [doc] Improve coqdoc output for header comments
  etc/utils/builddoc_lib.sh
  mathcomp/Makefile.common
Labels: TODO: MC-1 port
