Repository math-comp/math-comp, pull requests merged in 2024-01, with the labels that each got.

#1144 doc title
  mathcomp/algebra/ssralg.v
Labels: TODO: MC-1 port

#1145 Change the scope of function notations in order.v and ssralg.v to `function_scope`
  mathcomp/algebra/ssralg.v
  mathcomp/ssreflect/order.v
Labels: kind: fix, TODO: MC-1 port

#1147 typo in opam file
  coq-mathcomp-algebra.opam
Labels: kind: documentation, TODO: MC-1 port

#1151 Remove warning silencing no longer used
  mathcomp/ssreflect/Make
Labels: TODO: MC-1 port

#1161 Synchronize opam file with repo
  coq-mathcomp-ssreflect.opam
Labels: TODO: MC-1 port
