Repository math-comp/math-comp, pull requests merged in 2025-04, with the labels that each got.

#1125 Add semi-modules, semi-algebras, and semilinear functions
  algebra/matrix.v
  algebra/mxalgebra.v
  algebra/mxpoly.v
  algebra/poly.v
  algebra/qpoly.v
  algebra/ssralg.v
  algebra/vector.v
  character/character.v
  character/classfun.v
  character/inertia.v
  character/mxabelem.v
  character/mxrepresentation.v
  doc/changelog/01-added/1125-semi-modules.md
  doc/changelog/02-changed/1125-semi-modules.md
  field/falgebra.v
  field/fieldext.v
Labels: kind: enhancement

#1388 Fix the header doc of ssralg and deprecation notations in countalg and finalg
  algebra/countalg.v
  algebra/finalg.v
  algebra/ssralg.v
Labels: kind: fix

#1393 Clean up build and config
  .gitignore
  .vscode/settings.json
  Makefile.common
Labels: kind: build

#1391 Fix minor issues in archimedean.v and amend changelog entries for #1250
  algebra/archimedean.v
  doc/changelog/01-added/1250-archimedean-mixin.md
  doc/changelog/02-changed/1250-archimedean-mixin.md
Labels: kind: fix

#1385 Generalize some results in matrix.v using potentally-zero (semi)rings
  algebra/matrix.v
  doc/changelog/02-changed/1385-propagate-pzrings.md
Labels: kind: enhancement

#1397 inr/inl_inj
  doc/changelog/01-added/1397-ssrfun_20250407.md
  ssreflect/ssrfun.v
Labels: kind: enhancement

#1417 fix typo in doc of image
  ssreflect/fintype.v
Labels: kind: documentation

#1296 Swap the order of the axioms for multiplicative
  algebra/fraction.v
  algebra/matrix.v
  algebra/mxpoly.v
  algebra/poly.v
  algebra/polyXY.v
  algebra/qpoly.v
  algebra/rat.v
  algebra/ring_quotient.v
  algebra/sesquilinear.v
  algebra/ssralg.v
  algebra/ssrint.v
  algebra/ssrnum.v
  character/character.v
  character/classfun.v
  character/inertia.v
  character/mxrepresentation.v
  doc/changelog/03-renamed/1296-1first.md
  field/algC.v
  field/algebraics_fundamentals.v
  field/algnum.v
  field/closed_field.v
  field/falgebra.v
  field/fieldext.v
  field/finfield.v
  field/galois.v
  field/separable.v
Labels: kind: fix
